name: Passing Values to Next Steps

on:  workflow_dispatch

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value using ENV Vars
      run: |
        echo "variableName=this-is-value" >> $GITHUB_ENV

# :: is used to invoke github action coomands and asign a value to varible in step 
    - name: Create-Variables
      id: var_source_step
      run: |
        # ::set-output is now depricated use "var1_name=TechSckool" >> $GITHUB_OUTPUT
        echo "Performing a random task"
        
        echo "::set-output name=var2_date::$(date +'%Y-%m-%d-%H-%M')"
        echo "var1_name=TechSckool" >> $GITHUB_OUTPUT
    

    - name: Get-Variable-Value
      run: |
        echo "Printing the values"
        echo variableName: ${{ env.variableName }} 
        # access steps look at all steps in this job gotto step id ver_source_step goto outputs and get value of the variable
        echo var1_name: ${{ steps.var_source_step.outputs.var1_name }} 
        echo var2_date: ${{ steps.var_source_step.outputs.var2_date }}

